Added reading passwords from file
You can now create a password list (default is ~/.unrar_passwords), which is a simple text file containing archive passwords (separated by newlines). If an archive needs a password, then unrarall will read the file in a top down manner and try to use each password until it finds the correct one or reaches EOF.

Please note, that this commit removes the ability to get asked for a password and input it manually. IMHO this is not needed, as this tool is clearly designed for mass extraction and should not wait for user input (this is also why the '-y' option is used in the code). If you need to extract an archive with a password, just put it in the passwords file  and remove the file afterwards (or just use plain unrar/7z).

This fixes arfoll/unrarall#13

diff --git a/unrarall b/unrarall
--- a/unrarall
+++ b/unrarall
@@ -32,6 +32,7 @@ declare -x UNRARALL_BIN="" #Leave empty to let unrarall to loop through UNRAR_BI
 declare -x UNRAR_BINARIES=(unrar 7z) #Array of binaries to try and use, the order here is the order of precedence
 declare -x UNRARALL_PID="$$"
 declare -x UNRARALL_EXECUTABLE_NAME=$(basename $0;)
+declare -x UNRARALL_PASSWORD_FILE="${HOME}/.unrar_passwords" #If this exists and unrar asks for a password
 declare -ax UNRARALL_DETECTED_CLEAN_UP_HOOKS
 declare -ax UNRARALL_CLEAN_UP_HOOKS_TO_RUN=(none)
 
@@ -498,12 +499,31 @@ for file in $(find "$DIR" -iregex '.*\.\(rar\|001\)$'); do
   # unrar file if SFV checked out or --force was given
   if [ "$SUCCESS" -eq 0 ] || [ "$FORCE" -eq 1 ]; then
     message nnl "Extracting (${UNRAR_METHOD}) \"$file\"..."
+    # Try extracting without a password
     if [ "$VERBOSE" -eq 1 ] || [ "$UNRARALL_BIN" = "echo" ] ; then
-      ${UNRARALL_BIN} ${UNRAR_METHOD} $( getUnrarFlags ${UNRARALL_BIN}) "$filename"
+      ${UNRARALL_BIN} ${UNRAR_METHOD} $( getUnrarFlags ${UNRARALL_BIN}) -p- "$filename"
     else
-      ${UNRARALL_BIN} ${UNRAR_METHOD} $( getUnrarFlags ${UNRARALL_BIN}) "$filename" >/dev/null
+      ${UNRARALL_BIN} ${UNRAR_METHOD} $( getUnrarFlags ${UNRARALL_BIN}) -p- "$filename" >/dev/null
     fi
     SUCCESS=$?
+    # If extracting without a password failed and we have a password file, then use it
+    if [ "$SUCCESS" -eq 3 ] && [ -s "$UNRARALL_PASSWORD_FILE" ] ; then
+        [ $VERBOSE -eq 1 ] && message info "Trying passwords from password file \"${UNRARALL_PASSWORD_FILE}\"..."
+        while true; do read password || break
+            if [ "$VERBOSE" -eq 1 ] || [ "$UNRARALL_BIN" = "echo" ] ; then
+              ${UNRARALL_BIN} ${UNRAR_METHOD} $( getUnrarFlags ${UNRARALL_BIN}) -p"$password" "$filename"
+            else
+              ${UNRARALL_BIN} ${UNRAR_METHOD} $( getUnrarFlags ${UNRARALL_BIN}) -p"$password" "$filename" >/dev/null
+            fi
+            SUCCESS=$?
+	    if [ "$SUCCESS" -eq 0 ] ; then
+                [ $VERBOSE -eq 1 ] && message ok "Correct password is: \"${password}\""
+                break
+            else
+                [ $VERBOSE -eq 1 ] && message error "Tried wrong password: \"${password}\""
+            fi
+	done < "$UNRARALL_PASSWORD_FILE"
+     fi
   fi
 
   # if fail remove from count
